name: AvNParty
version: ${project.version}
main: net.playavalon.avnparty.AvNParty
api-version: 1.16
authors: [ MarcatoSound ]
commands:
  party:
    description: The core party command.
  p:
    description: Shorthand for the party chat command.
